### PR TITLE
Fix hang if build does not start

### LINKED ISSUE #271: Buildalyzer hangs if build does not start
@martincostello found that adding global properties with `;` in would result in Buildalyzer hanging.

I've done some investigating and have created a minimal repro here:
https://github.com/phmonte/Buildalyzer/compare/main...slang25:Buildalyzer:msbuild-hang-repro

If you run that test you will see that it just hangs. There are really two issues here, the first is minor, which is that we should escape [the property values as outlined here](https://github.com/dotnet/msbuild/issues/471#issuecomment-366268743) to work around the fact that msbuild doesn't like `;` in property values.

The second is a bit more fundamental, if the build doesn't start for _whatever_ reason, Buildalyzer should not hang. I've been thinking about this and looking into the best way of supporting this, and there's not an obvious fix due to the way `AnonymousPipeLoggerServer` works, but the simple workaround I've found is to dispose of the underlying stream when:
1. We've received no build events
2. The process has exited with a non-zero return code

With this in place we should still get an overall result from Buildalyzer, but with an `OverallSuccess` of `false` as expected.

I'll create two PRs, one fixing the value escaping, the other with a (not ideal) fix for the general hang scenario.

### PR DESCRIPTION
**Pull request by slang25**
Fixes #271

There are other solutions to this, like running `ReadAll` in a `Thread` or `Task` and aborting that. I've also looked at the cancellation token and using that, however it's not being used effectively in `ReadAll` and I don't think there is simple solution as `AnonymousPipeLoggerServer` doesn't support cooperative cancellation as far as I can see.

There may be a memory leak here with the the two events being subscribed to, not sure if we want to try and engineer a better solution.

### CODE REVIEW

File: src/Buildalyzer/ProjectAnalyzer.cs [hunk 1]
```diff
@@ -170,8 +172,22 @@ public IAnalyzerResults Build(string[] targetFrameworks, BuildEnvironment buildE
                 GetEffectiveEnvironmentVariables(buildEnvironment),
                 Manager.LoggerFactory))
             {
+                processRunner.Exited += () =>
+                {
```
Comment (Corniel) [inline src/Buildalyzer/ProjectAnalyzer.cs:176]: I'm not sure if there is a convention specified for this, but I prefer a method being assigned here.

Comment (slang25) [reply src/Buildalyzer/ProjectAnalyzer.cs:183]: I've changed these event handlers to local functions 👍

**Comment by phmonte** [comment]
Thanks for the contribution @slang25 .
